git-practice/#50-tsumura-lunchからstagingへのマージ(git-practice/#50)
matsuo-y/git-practice-lunch pull request #88
Opened 2017-04-05 04:40 UTC by opst-tsumura

## 関連チケット
- connect matsuo-y/git-practice#50

## 修正内容
- 修正内容を記載
- 修正前後の画面比較

before | after
---- | ----

<img src="" width="320"/> | <img src="" width="320"/>

## 判定基準
- [ ] 修正内容が適用されていることを[heroku のreview app環境](https://git-practice-lunch-pr-{N}.herokuapp.com)で確認できた
- [ ] ブランチが適切なブランチから作成されていることを [Network](https://github.com/matsuo-y/git-practice-lunch/network)で確認できた
- [ ] プルリク先に適切なブランチが選択されていることを確認できた

2017-04-05 04:44 UTC, opst-tsumura commented
@opst-ezaki stagingへのPRをを作成したので、確認をお願いします。

2017-04-05 04:46 UTC, ghost requested changes
判定基準の

> 修正内容が適用されていることをheroku のreview app環境で確認できた

のリンクが誤っているようですので、修正お願いいたします。

2017-04-05 04:51 UTC, opst-tsumura commented
@opst-ezaki 修正しました

2017-04-05 04:51 UTC, ghost submitted a review, later dismissed

2017-04-05 04:52 UTC, opst-ezaki commented
確認できました。
現在のstagingがmasterに上がり次第、mergeします。

2017-04-05 05:57 UTC, opst-ezaki commented
すみません、先に #89 を staging に上げてしまったので、
こちらが master に上がってからstagingに上げます。

2017-04-05 06:20 UTC, opst-tsumura commented
@opst-oshima すみません、アサイン先が間違っていたので、修正しました。
一旦レビューだけお願いします。（マージはのちほど）

2017-04-05 09:17 UTC, opst-oshima commented
```
before | after
---- | ----
![fireshot capture 29 - lunch history 2017 04_ - https___staging-git-practice-lunch](https://cloud.githubusercontent.com/assets/12555037/24690118/d37b865e-1a05-11e7-9649-c77666f8f1c7.png) | 
![fireshot capture 28 - lunch history 2017 04_ - https___git-practice-lunch-pr-88 h](https://cloud.githubusercontent.com/assets/12555037/24690122/d8af7dce-1a05-11e7-8383-4d7f45dfcfe9.png)
```
```
before | after
---- | ----
![fireshot capture 29 - lunch history 2017 04_ - https___staging-git-practice-lunch](https://cloud.githubusercontent.com/assets/12555037/24690118/d37b865e-1a05-11e7-9649-c77666f8f1c7.png) | ![fireshot capture 28 - lunch history 2017 04_ - https___git-practice-lunch-pr-88 h](https://cloud.githubusercontent.com/assets/12555037/24690122/d8af7dce-1a05-11e7-8383-4d7f45dfcfe9.png)
```



@opst-tsumura 
細かいですが、上記を下記のようにすれば貼ったスクリーンショットのレイアウトが綺麗になります。(beforeとafterで綺麗に分かれる)
後はスクショの方ですが、できればフルスクリーンで撮るのではなく、上記にurlを載せた状態でスクリーンショットを撮るようにお願いします。

2017-04-05 10:33 UTC, opst-tsumura commented
@opst-oshima 修正しました。確認お願いします。

2017-04-06 04:49 UTC, opst-tsumura commented
@opst-ezaki 本日大島さんがお休みですので、江嵜さんに回します。検収よろしくお願いします。

2017-04-06 04:50 UTC, ghost approved these changes
確認しました。マージします。

2017-04-06 04:50 UTC, merged